### ISSUE TITLE
cc to low

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/topic-types#15]

**Comment by qunabu** [comment]
https://codecov.io/gh/EscolaLMS/topic-types/tree/acf25f019baf3c4883f1a44085b32567d38a2ed5/src 
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/214608/158389069-5e0c85bd-79ab-430c-ab57-46778a8f5ccf.png">

**Comment by KrzysztofDziedziechEscolasoft** [comment]
CC is now 84%
